#:schema https://github.com/joshmedeski/sesh/raw/main/sesh.schema.json

[[session]]
name = "dotfiles"
path = "~/.dotfiles"
startup_command = "v"

[[session]]
name = "cupid-2.0"
path = "~/Projects/cupid-2.0"
startup_command = "v"
windows = ["docker", "lazydocker", "lazygit"]

[[session]]
name = "2541-website"
path = "~/Projects/2541-website"
startup_command = "v"
windows = ["terminal", "lazygit", "agents"]

[[window]]
name = "terminal"
startup_script = ""

[[window]]
name = "docker"
startup_script = ""

[[window]]
name = "agents"
startup_script = ""

[[window]]
name = "lazygit"
startup_script = "lazygit"

[[window]]
name = "lazydocker"
startup_script = "lazydocker"
